# yml file for Appveyor
# Based of Reference at: https://www.appveyor.com/docs/appveyor-yml/
#
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.0-alpha.{branch}.{build}

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Ubuntu

# set clone depth
clone_depth: 10

matrix:
  fast_finish: true

environment:
  matrix:
    - ARCH: 32bit
      MSYSTEM: Ubuntu32
    - ARCH: 64bit
      MSYSTEM: Ubuntu64


for:
-
  matrix:
    except:
      - ARCH: 64bit
      - APPVEYOR_REPO_TAG: true
  only_commits:
    files:
      - lib/*.cpp
-
  skip_commits:
    files:
      - .travis.yml

#---------------------------#
#    Run build commands     #
#---------------------------#

init:
  - bash -c 'mkdir -p out; pwd; ls;'

install:
  - bash -c 'echo "$APPVEYOR_BUILD_FOLDER" > out/1_initial.txt'

build_script:
  - bash -c 'echo "$ARCH $MSYSTEM" > out/2_building.txt'

test_script:
  - bash -c 'echo "Now testing $ARCH $MSYSTEM" > out/3_building.txt'

after_test:
  - bash -c "ls *' > out/4_final.txt"


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: 'out\*'
